### ISSUE TITLE
[SRML Contract] Zero Fees Causes Contract Instantiation Failure

### ISSUE THREAD

**Issue by charles-salmon** [cennznet/plug-blockchain#21]
Our use case does not require network/transfer fees of any kind to be charged to participants.

Accordingly, we set the `contract` key in the `GenesisConfig` to:

```rust
        Some(ContractConfig {
            signed_claim_handicap: 2,
            rent_byte_price: 4,
            rent_deposit_offset: 1000,
            storage_size_offset: 8,
            surcharge_reward: 0,
            tombstone_deposit: 16,
            transaction_base_fee: 0,
            transaction_byte_fee: 0,
            transfer_fee: 0,
            creation_fee: 0,
            contract_fee: 0,
            call_base_fee: 0,
            create_base_fee: 0,
            gas_price: 0,
            max_depth: 1024,
            block_gas_limit: 10_000_000,
            current_schedule: Default::default(),
        })
```

Upon deploying a contract and attempting to instantiate this, using `@cennznet/api` to sign and send an extrinsic of the form:

```typescript
(this.$api.tx.contract.create(
      0,
      500000, // If this is set to `0`, we get an `ExtrinsicFailed` back
      hash,
      abi.deploy()
    ) as unknown) as SubmittableExtrinsic<Promise<Codec>, Promise<() => any>>;
```

the callback notified us that the extrinsic was `Invalid`.

The node output:

```
/rustc/991c719a1d0f95c37ed7ea56bdb38bcc2a6246b9/src/libcore/ops/arith.rs
443
45
```

which points to a [division by zero error](https://github.com/rust-lang/rust/blob/991c719a1d0f95c37ed7ea56bdb38bcc2a6246b9/src/libcore/ops/arith.rs#L443).

Upon reconfiguring the genesis block with the following configuration:

```rust
        Some(ContractConfig {
            signed_claim_handicap: 2,
            rent_byte_price: 4,
            rent_deposit_offset: 1000,
            storage_size_offset: 8,
            surcharge_reward: 1,
            tombstone_deposit: 16,
            transaction_base_fee: 1,
            transaction_byte_fee: 1,
            transfer_fee: 1,
            creation_fee: 1,
            contract_fee: 1,
            call_base_fee: 1,
            create_base_fee: 1,
            gas_price: 1,
            max_depth: 1024,
            block_gas_limit: 10_000_000,
            current_schedule: Default::default(),
        })
```

it is possible to deploy and instantiate a contract successfully, although not in a way that supports our use case.

**Comment by shaopengw** [comment]
The division by zero is caused in gas calculation. https://github.com/cennznet/plug-blockchain/blob/e61677b4de8873cc243f77e2d3a37f788a8aea43/srml/contract/src/gas.rs#L260-L263

I would investigate a proper fix of this. If urgent, a temp workaround in genesis config could be set fees as `0` but `gas_price` as `1`, and it would not actually charge fees.
