### ISSUE TITLE
Re-instate dual-token modifications to `srml/staking`

### ISSUE THREAD

**Issue by jordy25519** [cennznet/plug-blockchain#58]
See: https://github.com/cennznet/plug-blockchain/blob/8cce3fb0d401ad20977af47052365e2ccebe8bd1/srml/staking/src/lib.rs#L1113-L1129

**Comment by cowboy-bebug** [comment]
Regarding the separation of concern (https://github.com/orgs/cennznet/projects/8#card-27890867), is it possible to keep any changes to core / srml in a separate repo or folder?
And then have a `build.sh` or something to copy & replace relevant scripts

**Comment by jordy25519** [comment]
I think it will be hard to automate with new changes from upstream and messy diffs it will continue to require a manual merge process.
The best outcome is to reduce the surface area / complexity of the merges when they do need to happen which is one of the goals of that issue.

We'll need to keep a changelog of the alterations to our fork in the forseeable future and have an end to end test suite to verify newly integrated upstream changes keep the functionality as expected

**Comment by cowboy-bebug** [comment]
Yep that sounds good!
