### ISSUE TITLE
Asset Ids are incorrect in Stable-Hotfix branch

### ISSUE THREAD

**Issue by mzxyz** [cennznet/plug-blockchain#69]
The asset_Id config in [stable-hotfix](https://github.com/cennznet/plug-blockchain/blob/45866b372a314add00dc826cbb3d42a68f55ab63/node/cli/src/chain_spec.rs#L188) branch is still using `[0, 1]`.

Should change to `[16000, 16001]`

**Comment by jordy25519** [comment]
The asset IDs are configured correctly in cennznet, plug doesn't need to know about or use 16000/160001. It think there was mix up between the `stable-hotfix` branches on cennznet/cennznet and cennznet/plug-blockchain

**Comment by mzxyz** [comment]
> mix up

Yes, you are right, will close this
