### ISSUE TITLE
Update Plug with Versioned Doughnut

### ISSUE THREAD

**Issue by mzxyz** [cennznet/plug-blockchain#75]
- [ ] Refactor Plug to use the new versioned Doughnut enum type
- [ ] May require creating and tagging a new release branch for doughnut-rs (includes Cargo.toml version bump)

This should be part of the Plug and CENNZnet 1.0.0-rc2 releases

**Comment by jordy25519** [comment]
This should be in plugblockchain/plug-blockchain

**Comment by mzxyz** [comment]
Roger that
